### ISSUE TITLE
Error when passing existing db object

### ISSUE THREAD

**Issue by MrSpark2591** [moscajs/aedes-persistence-mongodb#16]
```
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at /Users/dhavalchaudhary/Desktop/bitbucket/fasal-mqtt-broker/node_modules/aedes-persistence-mongodb/persistence.js:61:31
    at MongoPersistence._connect (/Users/dhavalchaudhary/Desktop/bitbucket/fasal-mqtt-broker/node_modules/aedes-persistence-mongodb/persistence.js:36:5)
    at MongoPersistence._setup (/Users/dhavalchaudhary/Desktop/bitbucket/fasal-mqtt-broker/node_modules/aedes-persistence-mongodb/persistence.js:53:8)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

I am passing existing db connection to the object : 

```
initializeDb((db) => {
  let settings = {
    mq: mq({
      db: db
    }),
    persistence: aedesPersistenceMongoDB({ db: db }),
    authenticate: authenticate,
    authorizePublish: authorizePublish,
    authorizeSubscribe: authorizeSubscribe
  };

  const app = aedes(settings);
  const server = net.createServer(app.handle);

  server.listen(config.app.port, () => {
    logger.info(`Borker is up and running on ${config.app.port}`);
  });
});
```

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by MrSpark2591** [comment]
Yeh sure. I will fix and send PR for your inputs.
