### ISSUE TITLE
Update document requires atomic operators

### ISSUE THREAD

**Issue by expandboard** [moscajs/aedes-persistence-mongodb#69]
i run cluster example with MongoDB, broker can handle publish with NOT retain flag but when i set Retain flag true, it rises this error;
/home/ioboard/mqttbroker/examples/clusters/node_modules/mongodb/lib/bulk/common.js:647
      throw new TypeError('Update document requires atomic operators');
      ^

TypeError: Update document requires atomic operators
    at FindOperators.updateOne (/home/ioboard/mqttbroker/examples/clusters/node_modules/mongodb/lib/bulk/common.js:647:13)
    at executeBulk (/home/ioboard/mqttbroker/examples/clusters/node_modules/aedes-persistence-mongodb/persistence.js:200:38)
    at MongoPersistence.storeRetained (/home/ioboard/mqttbroker/examples/clusters/node_modules/aedes-persistence-mongodb/persistence.js:185:3)
    at PublishState.storeRetained (/home/ioboard/mqttbroker/examples/clusters/node_modules/aedes/aedes.js:166:29)
    at makeCallTwo (/home/ioboard/mqttbroker/examples/clusters/node_modules/fastseries/series.js:150:3)
    at release (/home/ioboard/mqttbroker/examples/clusters/node_modules/fastseries/series.js:138:7)
    at resultList (/home/ioboard/mqttbroker/examples/clusters/node_modules/fastseries/series.js:125:3)
    at Aedes.series [as _series] (/home/ioboard/mqttbroker/examples/clusters/node_modules/fastseries/series.js:45:7)
    at Aedes.publish (/home/ioboard/mqttbroker/examples/clusters/node_modules/aedes/aedes.js:257:8)
    at Client.enqueuePublish (/home/ioboard/mqttbroker/examples/clusters/node_modules/aedes/lib/handlers/publish.js:60:21)
Worker 204140 died with code: 1, and signal: null
Starting a new worker
Worker 206756 is online

what's wrong here?

**System Information**
- Aedes: 0.44
- NodeJS: v10.19.0
- OS: Ubuntu 20
- Arch: x86_64

**Comment by robertsLando** [comment]
Based on the error you shown, seems the problem is happening [here](https://github.com/moscajs/aedes-persistence-mongodb/blob/master/persistence.js#L262-L268). 

BTW by looking at the mongodb [docs](http://mongodb.github.io/node-mongodb-native/4.0/classes/orderedbulkoperation.html) I cannot find what's wrong in that code.

What version of aedes are you using? If you are using 0.45.0 this could be related to our last change where we removed the retain false in broker publish method, this in a cluster env could make multiuple aedes instances calling the bulk write to the same document (?)  

@mcollina @getlarge any thoughts?

**Comment by getlarge** [comment]
@robertsLando,  @expandboard  metioned to use aedes v0.44 so the latest changes should not be the reason for this issue.

I cannot help regarding this persistence module and mongo bulkOperation, sorry. My naive approach would be to reproduce this situation and add some log and error catchers to know more about it.

**Comment by robertsLando** [comment]
@KevinVitale IMO the problem is that upsert is not atomic and could create errors in cluster enviroments here: 

https://github.com/moscajs/aedes-persistence-mongodb/blob/master/persistence.js#L269

I think you could give a try by using http://mongodb.github.io/node-mongodb-native/4.0/classes/bulkoperationbase.html#handlewriteerror
